version: "3.8"

services:
  sut:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pipenv run python manage.py test'
    depends_on:
      - db
  db:
     image: postgres
     environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
