version: "3.8"

services:
  sut:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./manage.py test --settings=naklario.test_settings'
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=key
      - DATABASE_URL=psql://docker:docker@db/docker
      - DEBUG=false
      - BBB_SHARED=1234
      - BBB_URL=https://bbb.example.com
      - API_URL=https://api.example.com
      - FRONTEND_URL=https://frontend.example.com
      - USE_S3=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_ADMINS=
      - SERVER_EMAIL=server@example.com
  db:
     image: postgres
     environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
  redis:
    image: redis:6
