version: "3.8"

services:
  sut:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./manage.py test --settings=naklario.test_settings'
    depends_on:
      - db
      - redis
  db:
     image: postgres
     environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
  redis:
    image: redis:6
