version: "3.8"

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
  db:
     image: postgres:12
     environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
     ports:
       - 5432:5432
     volumes:
       - type: volume
         source: database
         target: /var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - type: volume
        source: minio
        target: /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=BTTn7RlN4cJ4CFwdqTImERRvO2tIqwgqmUllWkPOxZwmsntrrQleFV9J0zgHF28r
      - MINIO_SECRET_KEY=dVwjhuM16MutpM27m9WUMlIwgS7x0o5vM6Z943co8alVQvNqSOmslSGIiB0MRXrr
volumes:
  database:
  minio:
