version: "3.8"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 naklario.asgi:application
    working_dir: /code/naklar-io
    volumes:
      - type: bind
        source: ./naklar-io
        target: /code/naklar-io
      - type: bind
        source: ./media
        target: /opt/media
      - type: volume
        source: static
        target: /opt/static

  smtpd:
    image: python:3.7
    command: python3 -m smtpd -n -c DebuggingServer 0.0.0.0:1025

  celery_worker:
    build: .
    working_dir: /code/naklar-io
    command: celery -A naklario worker -l info
    volumes:
      - ./naklar-io/naklario/settings_local.py:/code/naklar-io/naklario/settings_local.py:ro
    depends_on:
      - rabbitmq
      - web

  celery_beat:
    build: .
    working_dir: /code/naklar-io
    command: celery -A naklario beat -S django -l info
    volumes:
      - ./naklar-io/naklario/settings_local.py:/code/naklar-io/naklario/settings_local.py:ro
    depends_on:
      - rabbitmq
      - web

  rabbitmq:
    image: rabbitmq

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: ./media
        target: /opt/media
      - type: volume
        source: static
        target: /opt/static
        volume:
          nocopy: true
    ports:
      - 8000:80

volumes:
  static:
