version: "3.8"

services:
  web:
    image: naklario/backend:latest
    volumes:
      # Private VAPID key https://github.com/jazzband/django-push-notifications/#settings-list
      - ./naklar-io/private_key.pem:/code/naklar-io/private_key.pem
      - type: bind
        source: ./media
        target: /opt/media
    env_file:
      - .env
    ports:
      - 8001:8000
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=psql://docker:docker@db/docker
      - DEBUG=false

  celery_worker:
    image: naklario/backend:latest
    command: python -m celery -A naklario worker
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=psql://docker:docker@db/docker
      - DEBUG=false

  celery_beat:
    image: naklario/backend:latest
    command: python -m celery -A naklario beat -S django
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=psql://docker:docker@db/docker
      - DEBUG=false

  redis:
    image: redis:6


volumes:
  database:

