version: "3.8"

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - type: volume
        source: minio
        target: /data
    environment:
      - MINIO_ACCESS_KEY=VJFJFJAWDEXAMPLEKEY
      - MINIO_SECRET_KEY=AWDJEFIEFIJSEFJEXAMPLEKEY
volumes:
  minio: